import minBy from './minBy.js';
import sortDesc from './sortDesc.js';
import go from './go.js';
import goS from './goS.js';
import identity from './identity.js';
import reduce from './reduce.js';
import reduceS from './reduceS.js';
import stop from './stop.js';
import stopIf from './stopIf.js';
import take from './take.js';
import omit from './omit.js';
import values from './values.js';
import groupBy from './groupBy.js';
import tap from './tap.js';
import pipe from './pipe.js';
import pipeS from './pipeS.js';
import isString from './isString.js';
import max from './max.js';
import pluck from './pluck.js';
import takeAll from './takeAll.js';
import countBy from './countBy.js';
import keys from './keys.js';
import isUndefined from './isUndefined.js';
import constant from './constant.js';
import unique from './unique.js';
import indexBy from './indexBy.js';
import min from './min.js';
import sortByDesc from './sortByDesc.js';
import noop from './noop.js';
import hi from './hi.js';
import extend from './extend.js';
import empty from './empty.js';
import takeWhile from './takeWhile.js';
import isMatch from './isMatch.js';
import mapEntries from './mapEntries.js';
import object from './object.js';
import negate from './negate.js';
import nop from './nop.js';
import call from './call.js';
import some from './some.js';
import deepFlat from './deepFlat.js';
import toIter from './toIter.js';
import maxBy from './maxBy.js';
import flat from './flat.js';
import baseSel from './baseSel.js';
import sortBy from './sortBy.js';
import not from './not.js';
import go1 from './go1.js';
import find from './find.js';
import isArray from './isArray.js';
import each from './each.js';
import entries from './entries.js';
import filter from './filter.js';
import sort from './sort.js';
import curry from './curry.js';
import isFunction from './isFunction.js';
import sel from './sel.js';
import match from './match.js';
import map from './map.js';
import head from './head.js';
import every from './every.js';
import has from './has.js';
import isIterable from './isIterable.js';
import uniqueBy from './uniqueBy.js';
import flatMap from './flatMap.js';
import string from './string.js';
import strMap from './strMap.js';
import findWhere from './findWhere.js';
import reject from './reject.js';
import pick from './pick.js';
import last from './last.js';
import take1 from './take1.js';
import tail from './tail.js';
import log from './log.js';
import takeUntil from './takeUntil.js';
import defaults from './defaults.js';
import calls from './calls.js';
import delay from './delay.js';
import safety from './safety.js';
import mapObject from './mapObject.js';
import promiseAllObject from './promiseAllObject.js';
import promiseAllEntries from './promiseAllEntries.js';
import isStop from './isStop.js';
import range from './range.js';
import drop from './drop.js';
import dropRight from './dropRight.js';
import { L } from './L.js';
import { C } from './C.js';

window.fx = window._ = {};
window.fx.L = window.L = L;
window.fx.C = window.C = C;

_.minBy = _.min_by = minBy;
_.sortDesc = _.sort_desc = sortDesc;
_.go = go;
_.goS = goS;
_.identity = identity;
_.reduce = reduce;
_.reduceS = reduceS;
_.stop = stop;
_.stopIf = _.stop_if = stopIf;
_.take = take;
_.omit = omit;
_.values = values;
_.groupBy = _.group_by = groupBy;
_.tap = tap;
_.pipe = pipe;
_.pipeS = pipeS;
_.isString = _.is_string = isString;
_.max = max;
_.pluck = pluck;
_.takeAll = _.take_all = takeAll;
_.countBy = _.count_by = countBy;
_.keys = keys;
_.isUndefined = _.is_undefined = isUndefined;
_.constant = constant;
_.unique = _.uniq = unique;
_.indexBy = _.index_by = indexBy;
_.min = min;
_.sortByDesc = _.sort_by_desc = sortByDesc;
_.noop = noop;
_.hi = hi;
_.extend = extend;
_.empty = empty;
_.takeWhile = _.take_while = takeWhile;
_.isMatch = _.is_match = isMatch;
_.mapEntries = _.map_entries = _.entriesMap = _.entries_map = mapEntries;
_.object = object;
_.negate = negate;
_.nop = nop;
_.call = call;
_.some = some;
_.deepFlat = _.deepFlatten = _.deep_flat = _.deep_flatten = deepFlat;
_.toIter = _.to_iter = toIter;
_.maxBy = _.max_by = maxBy;
_.flat = _.flatten = flat;
_.baseSel = _.base_sel = baseSel;
_.sortBy = _.sort_by = sortBy;
_.not = not;
_.go1 = go1;
_.find = find;
_.isArray = _.is_array = isArray;
_.each = each;
_.entries = entries;
_.filter = filter;
_.sort = sort;
_.curry = curry;
_.isFunction = _.is_function = isFunction;
_.sel = sel;
_.match = match;
_.map = map;
_.head = head;
_.every = every;
_.has = has;
_.isIterable = _.is_iterable = isIterable;
_.uniqueBy = _.unique_by = uniqueBy;
_.flatMap = _.flat_map = flatMap;
_.string = string;
_.strMap = _.str_map = _.scat = strMap;
_.findWhere = _.find_where = findWhere;
_.reject = reject;
_.pick = pick;
_.last = last;
_.take1 = take1;
_.tail = tail;
_.log = log;
_.takeUntil = _.take_until = takeUntil;
_.defaults = defaults;
_.calls = calls;
_.delay = delay;
_.safety = safety;
_.mapObject = _.map_object = mapObject;
_.promiseAllObject = _.promise_all_object = promiseAllObject;
_.promiseAllEntries = _.promise_all_entries = promiseAllEntries;
_.isStop = _.is_stop = isStop;
_.range = range;
_.drop = drop;
_.dropRight = _.drop_right = dropRight;